import io
import os
import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt
from PIL import Image, ImageOps
from pillow_heif import register_heif_opener
from scipy.ndimage import gaussian_filter1d
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
from segment_anything import sam_model_registry, SamPredictor

# CONFIG
IMAGE_PATH = "C:/Users/sidne/OneDrive/Bureau/Fall2026/SNSF-Opti-SARA/images/IMG_9292.jpg"
SAM_CHECKPOINT = "C:/Users/sidne/OneDrive/Bureau/Fall2026/SNSF-Opti-SARA/optiframe/src/sam_vit_h_4b8939.pth"
PROMPT = "eyeglass lens."          # lowercase, ends with a period
BOX_THRESHOLD, TEXT_THRESHOLD = 0.3, 0.25
MAX_SIDE = 2048                    # larger = better ArUco corner precision

# ---- Printed sheet (generated by the Letter sheet script) ----
SHEET_W, SHEET_H = 215.9, 279.4    # US Letter in mm
MARKER_MM = 50.0                   # outer black square, border included (verify with a ruler!)
ARUCO_DICT = cv2.aruco.DICT_4X4_50
VALID_IDS = {0, 1, 2, 3, 4, 5}
MIN_MARKERS = 3                    # refuse to measure with fewer markers

# Marker CENTERS in mm. Origin = top-left of the sheet, y down.
EDGE = 35.0
LAYOUT = {
    0: (EDGE, EDGE),                           # top-left
    1: (SHEET_W - EDGE, EDGE),                 # top-right
    2: (EDGE, SHEET_H / 2),                    # middle-left
    3: (SHEET_W - EDGE, SHEET_H / 2),          # middle-right
    4: (EDGE, SHEET_H - EDGE),                 # bottom-left
    5: (SHEET_W - EDGE, SHEET_H - EDGE),       # bottom-right
}

PX_PER_MM = 8                      # resolution of the rectified image (not an accuracy parameter)

EYE = "right"                      # "right" or "left" (comes from the app)
PHOTOGRAPHED_FROM_BACK = False     # True -> mirror x to get the wearer's view
ALIGN_TO_PRINCIPAL_AXES = True     # rotate the lens so A/B are measured along its own axes

OUT = "output"
os.makedirs(OUT, exist_ok=True)
register_heif_opener()
device = "cuda" if torch.cuda.is_available() else "cpu"


# MODEL LOADING — runs once when this module is imported (i.e. at server start).
# Previously these were instantiated inside `segment_lenses()` on every request,
# which reloaded ~1GB of weights per call and made each API request take several
# extra seconds. Loading them once at module scope keeps them resident in memory
# and reused across all subsequent calls.
print("[finalSam] Loading Grounding DINO model...")
_MODEL_ID = "IDEA-Research/grounding-dino-tiny"
_processor = AutoProcessor.from_pretrained(_MODEL_ID)
_dino = AutoModelForZeroShotObjectDetection.from_pretrained(_MODEL_ID).to(device)

print("[finalSam] Loading SAM (ViT-H) model...")
_sam = sam_model_registry["vit_h"](checkpoint=SAM_CHECKPOINT)
_sam.to(device)
_predictor = SamPredictor(_sam)
print("[finalSam] Models ready.")


# 0. LOAD
def load_image(path, max_side=MAX_SIDE):
    img = ImageOps.exif_transpose(Image.open(path)).convert("RGB")
    img.thumbnail((max_side, max_side))
    return img, np.array(img)


def load_image_from_bytes(data: bytes, max_side=MAX_SIDE):
    """Load an image from raw bytes (used by the Flask server)."""
    img = ImageOps.exif_transpose(Image.open(io.BytesIO(data))).convert("RGB")
    img.thumbnail((max_side, max_side))
    return img, np.array(img)


def process_image(data: bytes, eye: str, from_back: bool = False, max_side=MAX_SIDE):
    """Full pipeline: bytes in -> list of contour dicts out.

    ``eye`` is ``"L"`` or ``"R"``; the Python code internally uses ``"left"``/``"right"``.
    Returns one contour per detected lens.
    """
    eye_str = "left" if eye == "L" else "right"

    img, image = load_image_from_bytes(data, max_side)

    # 1. Segment
    boxes, masks = segment_lenses(img, image)

    # 2. Rectify
    found = detect_markers(image)
    H_mm, err = compute_homography_mm(found)
    rectified, H_px, size = rectify(image, H_mm)

    # 3. Measure each lens
    results = []
    for k, mask_u8 in enumerate(masks):
        mask_rect = cv2.warpPerspective(mask_u8, H_px, size, flags=cv2.INTER_NEAREST)
        res = measure(mask_rect, eye=eye_str, from_back=from_back)
        results.append(res)

    return results


# 1. SEGMENT (DINO + SAM)
def segment_lenses(img, image):
    # Reuse the module-level Grounding DINO processor/model (loaded once at import time).
    inputs = _processor(images=img, text=PROMPT, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = _dino(**inputs)
    results = _processor.post_process_grounded_object_detection(
        outputs, inputs.input_ids,
        threshold=BOX_THRESHOLD, text_threshold=TEXT_THRESHOLD,  # 'box_threshold=' on older versions
        target_sizes=[img.size[::-1]],
    )[0]
    boxes = results["boxes"].cpu().numpy()
    if len(boxes) == 0:
        raise RuntimeError("lens_not_found")

    # Reuse the module-level SAM predictor; set_image() must run per image
    # (it computes the image embedding), but the model weights stay loaded.
    _predictor.set_image(image)

    masks = []
    for box in boxes:
        m, _, _ = _predictor.predict(box=box, multimask_output=False)
        masks.append((m[0] * 255).astype(np.uint8))
    return boxes, masks


# 2. RECTIFY (ArUco -> mm)
def detect_markers(image):
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    params = cv2.aruco.DetectorParameters()
    params.adaptiveThreshWinSizeMax = 63                       # tolerant to uneven lighting
    params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX  # sub-pixel corners
    det = cv2.aruco.ArucoDetector(cv2.aruco.getPredefinedDictionary(ARUCO_DICT), params)
    corners, ids, _ = det.detectMarkers(gray)
    if ids is None:
        raise RuntimeError("no_reference")
    found = {int(i): c.reshape(4, 2) for c, i in zip(corners, ids.flatten()) if int(i) in VALID_IDS}
    if len(found) < MIN_MARKERS:
        raise RuntimeError(f"no_reference: only {len(found)} valid marker(s) found: {sorted(found)}")
    return found


def compute_homography_mm(found):
    """Image px -> sheet mm (origin top-left of the sheet, y down). Also returns reprojection error."""
    h = MARKER_MM / 2
    local = np.array([[-h, -h], [h, -h], [h, h], [-h, h]], np.float32)  # TL, TR, BR, BL
    src, dst = [], []
    for i, c in found.items():
        src.append(c)
        dst.append(local + np.array(LAYOUT[i], np.float32))
    src = np.vstack(src).astype(np.float32)
    dst = np.vstack(dst).astype(np.float32)

    H, _ = cv2.findHomography(src, dst, cv2.RANSAC, 1.0)
    proj = cv2.perspectiveTransform(src.reshape(-1, 1, 2), H).reshape(-1, 2)
    err = np.linalg.norm(proj - dst, axis=1)
    return H, err


def rectify(image, H_mm):
    """Warp the photo so the whole Letter sheet is upright at PX_PER_MM."""
    S = np.diag([PX_PER_MM, PX_PER_MM, 1.0])
    H_px = S @ H_mm
    size = (int(SHEET_W * PX_PER_MM), int(SHEET_H * PX_PER_MM))
    return cv2.warpPerspective(image, H_px, size), H_px, size


# 3. MEASURE
def measure(mask_rect, eye=EYE, from_back=PHOTOGRAPHED_FROM_BACK, n=200):
    cnts, _ = cv2.findContours(mask_rect, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        raise RuntimeError("lens_not_found")
    c = max(cnts, key=cv2.contourArea).reshape(-1, 2).astype(np.float64)

    # uniform resampling along the closed contour, then periodic smoothing
    closed = np.vstack([c, c[:1]])
    d = np.r_[0, np.cumsum(np.linalg.norm(np.diff(closed, axis=0), axis=1))]
    t = np.linspace(0, d[-1], n, endpoint=False)
    pts = np.c_[np.interp(t, d, closed[:, 0]), np.interp(t, d, closed[:, 1])]
    pts = gaussian_filter1d(pts, sigma=2, axis=0, mode="wrap")

    pts = pts / PX_PER_MM          # px -> mm
    pts[:, 1] *= -1                # y up
    pts -= pts.mean(0)

    if ALIGN_TO_PRINCIPAL_AXES:    # rotate so the long axis is along x
        _, _, vt = np.linalg.svd(pts, full_matrices=False)
        R = vt
        pts = pts @ R.T
        if np.linalg.det(R) < 0:   # keep a pure rotation (no accidental mirror)
            pts[:, 1] *= -1

    if from_back:                  # wearer's view
        pts[:, 0] *= -1

    A, B = np.ptp(pts[:, 0]), np.ptp(pts[:, 1])
    perimeter = np.linalg.norm(np.diff(np.vstack([pts, pts[:1]]), axis=0), axis=1).sum()
    return {"eye": eye, "points": pts.tolist(), "A": A, "B": B, "perimeter": perimeter}

def main_func():
    img, image = load_image(IMAGE_PATH)
    print("Image size:", image.shape)

    print("Segmenting lens...")
    boxes, masks = segment_lenses(img, image)
    print(f"{len(masks)} lens(es) detected")

    print("Detecting ArUco markers...")
    found = detect_markers(image)
    print("Markers found:", sorted(found))
    H_mm, err = compute_homography_mm(found)
    print(f"Homography reprojection error: mean={err.mean():.2f} mm, max={err.max():.2f} mm")
    if err.max() > 1.0:
        print("WARNING: error > 1 mm. Check MARKER_MM, LAYOUT, print scale, and sheet flatness.")

    rectified, H_px, size = rectify(image, H_mm)

    # Debug: detected markers with IDs
    dbg = image.copy()
    for i, c in found.items():
        cv2.polylines(dbg, [c.astype(int)], True, (0, 255, 0), 4)
        cx, cy = c.mean(0).astype(int)
        cv2.putText(dbg, str(i), (cx - 20, cy + 20), cv2.FONT_HERSHEY_SIMPLEX, 3, (255, 0, 0), 6)
    Image.fromarray(dbg).save(f"{OUT}/markers_debug.png")
    Image.fromarray(rectified).save(f"{OUT}/rectified.png")

    # Measure each lens
    rect_overlay = rectified.copy()
    for k, mask_u8 in enumerate(masks):
        mask_rect = cv2.warpPerspective(mask_u8, H_px, size, flags=cv2.INTER_NEAREST)
        Image.fromarray(mask_rect).save(f"{OUT}/mask_rectified_{k}.png")
        res = measure(mask_rect)
        print(f"Lens {k}: A={res['A']:.2f} mm  B={res['B']:.2f} mm  "
              f"perimeter={res['perimeter']:.1f} mm")

        cnts, _ = cv2.findContours(mask_rect, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        cv2.drawContours(rect_overlay, cnts, -1, (255, 0, 0), 3)

        pts = np.array(res["points"])
        fig, ax = plt.subplots(figsize=(5, 5))
        ax.plot(*np.vstack([pts, pts[:1]]).T, "-b")
        ax.set_aspect("equal"); ax.grid(True)
        ax.set_title(f"Lens {k}: A={res['A']:.1f} B={res['B']:.1f} mm")
        ax.set_xlabel("mm"); ax.set_ylabel("mm")
        fig.savefig(f"{OUT}/contour_mm_{k}.png", dpi=150, bbox_inches="tight")
        plt.close(fig)

    Image.fromarray(rect_overlay).save(f"{OUT}/rectified_overlay.png")
    print(f"Saved debug images to ./{OUT}/")

def test():
    return "Ceci est un test"
# MAIN
if __name__ == "__main__":
    main_func()